test_that("empty and rare fits have explicit sample accounting", {
  X <- diag(3)
  fit <- linf.csts(X, n0 = 2, low.freq.policy = "absorb")
  expect_warning(out <- summary(fit), NA)
  expect_equal(out$input.samples, 3L)
  expect_equal(out$assigned.samples, 0L)
  expect_equal(out$unassigned.samples, 3L)
  expect_equal(out$total.samples, out$assigned.samples)
  expect_true(all(is.na(out[c("mean.size", "median.size", "min.size", "max.size")])))
  expect_output(print(fit), "No assigned lineages")
  pure <- summary(dcst.view(fit, "pure"))
  expect_equal(pure$rare.samples, 3L)
  expect_equal(pure$n.lineages, 1L)
  expect_equal(pure$retained.lineages, 0L)
  expect_equal(pure$assigned.samples, 3L)
  expect_output(print(dcst.view(fit, "pure")), "No retained lineages")
})

test_that("summary denominators and terminal levels remain consistent", {
  X <- rbind(c(A = 10, B = 1), c(A = 9, B = 2), c(A = 0, B = 0))
  f <- linf.csts(X, n0 = 2)
  f <- refine.linf.csts(X, f, n0 = 5, verbose = FALSE)
  out <- summary(f)
  expect_equal(out$input.samples, c(3L, 3L))
  expect_equal(out$input.samples, out$assigned.samples + out$unassigned.samples)
  expect_equal(out$rare.samples, c(1L, 1L))
  expect_equal(out$retained.lineages, c(1L, 1L))
  expect_equal(out$min.size, c(1, 1))
  expect_equal(out$max.size, c(2, 2))
})

test_that("printing bounds the group list and returns the original object", {
  f <- linf.csts(diag(15), n0 = 1)
  text <- capture.output(result <- withVisible(print(f)))
  expect_true(any(grepl("5 more lineages", text)))
  expect_equal(result$value, f)
  expect_false(result$visible)
})
